#!/usr/bin/env python3
# run with tools/.venv/bin/python3 on the driver (numpy, matplotlib live in the venv); post-block.sh does
"""Field score over time, projected one and two weeks out (PROMPTS 28-30).
   tools/field-score.py [--plot progress/field-score.png] [--tau 1.0]

The field score (a build's expected score against every ladder bot, one game each) is a bounded percentage that
compresses as it rises, so it is not fitted directly. The RATING is: R(t) = R0 + a * ln(1 + t / tau), a
diminishing-returns curve (tau in days, default 1), weighted least squares over the submissions (g_iterN) with
weights 1 / SE^2, with a 95% band from the fit's covariance. The fitted and projected ratings are mapped to field
scores through elolib.field_score against the current ladder ratings, so the projection stays inside 0-100 by
construction. Every build is a point, dated by its first scrimmage block; candidates are shown hollow and are not
fitted. Regenerated by post-block.sh after every block, so the projection firms up as the record grows."""
import argparse, os, re, sys, datetime as dt
import numpy as np
here = os.path.dirname(os.path.abspath(__file__)); repo = os.path.dirname(here)
sys.path.insert(0, here); import elolib
a = argparse.ArgumentParser(); a.add_argument('--plot', default=os.path.join(repo, 'progress', 'field-score.png')); a.add_argument('--tau', type=float, default=1.0)
o = a.parse_args()
rows = elolib.load(); R, SE, games, wins = elolib.fit(rows); bots = elolib.ladder_bots()
first = {}
for r in rows:
    for b in (r['teamA'], r['teamB']):
        if elolib.is_ours(b):
            d = dt.datetime.strptime(r['run'][:15], '%Y%m%d-%H%M%S'); first[b] = min(first.get(b, d), d)
pts = sorted((first[p], p) for p in first if p in R and games.get(p, 0) >= 48)
subs = [(d, p) for d, p in pts if re.match(r'us:g_iter\d+$', p)]
if len(subs) < 3: sys.exit('fewer than three submissions to fit')
t0 = subs[0][0]
def days(d): return (d - t0).total_seconds() / 86400
def score(r):
    R2 = dict(R); R2['proj'] = r; return 100 * elolib.field_score(R2, 'proj', bots)
xs = np.array([np.log1p(days(d) / o.tau) for d, _ in subs]); ys = np.array([R[p] for _, p in subs]); w = np.array([1 / SE[p] for _, p in subs])
(aa, r0), cov = np.polyfit(xs, ys, 1, w=w, cov='unscaled')
def proj(t):
    x = np.log1p(t / o.tau); r = r0 + aa * x; s = np.sqrt(cov[0, 0] * x * x + 2 * cov[0, 1] * x + cov[1, 1]); return r, 1.96 * s
now = dt.datetime.utcnow(); tn = days(now)
print('submissions:', ', '.join(f'{p[3:]} {R[p]:.0f}+-{1.96 * SE[p]:.0f} ({d:%m-%d %H:%M}) {score(R[p]):.1f}%' for d, p in subs))
print(f'rating fit R = {r0:.0f} + {aa:.0f} ln(1 + t/{o.tau:g} d) (t in days from {t0:%Y-%m-%d %H:%M} UTC)')
for k in (0, 7, 14):
    r, e = proj(tn + k); print(f'  +{k:2d}d: rating {r:.0f} +- {e:.0f}  ->  field score {score(r):.1f}% [{score(r - e):.1f}%, {score(r + e):.1f}%]')
import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9.5, 8), sharex=True)
tt = np.linspace(0, tn + 14, 200); dates = [t0 + dt.timedelta(days=t) for t in tt]
rr = np.array([proj(t)[0] for t in tt]); ee = np.array([proj(t)[1] for t in tt])
cand = [(d, p) for d, p in pts if (d, p) not in subs]
# rating panel
ax1.errorbar([d for d, _ in subs], ys, yerr=[1.96 * SE[p] for _, p in subs], fmt='o', color='tab:blue', ms=5, capsize=2, label='submission (rating +- 95%)', zorder=3)
if cand: ax1.plot([d for d, _ in cand], [R[p] for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate (not fitted)')
for d, p in subs: ax1.annotate(p[3:], (d, R[p]), textcoords='offset points', xytext=(4, 5), fontsize=7)
past = tt <= tn
ax1.plot(np.array(dates)[past], rr[past], '-', color='tab:blue', lw=1.2, label=f'fit: R = {r0:.0f} + {aa:.0f} ln(1 + t/{o.tau:g}d)')
ax1.plot(np.array(dates)[~past], rr[~past], '--', color='tab:blue', lw=1.2, label='projection'); ax1.fill_between(dates, rr - ee, rr + ee, color='tab:blue', alpha=.12, label='95% band')
ax1.axvline(now, color='0.6', lw=0.8, ls=':'); ax1.set_ylabel('rating (Bradley-Terry, Elo scale)'); ax1.grid(alpha=.3); ax1.legend(fontsize=8, loc='lower right')
ax1.set_title('Rating by submission with a diminishing-returns fit, and the field score it implies')
# field-score panel
ss = np.array([score(r) for r in rr]); lo = np.array([score(r) for r in rr - ee]); hi = np.array([score(r) for r in rr + ee])
ax2.plot([d for d, _ in subs], [score(R[p]) for _, p in subs], 'o', color='tab:blue', ms=5, zorder=3, label='submission')
if cand: ax2.plot([d for d, _ in cand], [score(R[p]) for _, p in cand], 'o', mfc='white', mec='tab:gray', ms=4, label='candidate')
ax2.plot(np.array(dates)[past], ss[past], '-', color='tab:blue', lw=1.2); ax2.plot(np.array(dates)[~past], ss[~past], '--', color='tab:blue', lw=1.2, label='projection (mapped rating)')
ax2.fill_between(dates, lo, hi, color='tab:blue', alpha=.12, label='95% band')
for k in (7, 14):
    r, e = proj(tn + k); d = now + dt.timedelta(days=k); ax2.plot([d], [score(r)], 's', color='tab:red', ms=6)
    ax2.annotate(f'+{k}d: {score(r):.1f}% [{score(r - e):.0f}-{score(r + e):.0f}]', (d, score(r)), textcoords='offset points', xytext=(-8, 8), fontsize=8, ha='right', color='tab:red')
ax2.axvline(now, color='0.6', lw=0.8, ls=':'); ax2.annotate('now', (now, ax2.get_ylim()[0]), textcoords='offset points', xytext=(3, 3), fontsize=7, color='0.4')
ax2.set_ylabel('field score (%): expected score vs every ladder bot'); ax2.set_xlabel('first scrimmage block (UTC)'); ax2.grid(alpha=.3); ax2.legend(fontsize=8, loc='lower right')
fig.autofmt_xdate(); fig.tight_layout(); fig.savefig(o.plot, dpi=120); print('wrote', o.plot)
